/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.github.edgar615.spring.jdbc;

import com.github.edgar615.util.db.PersistentKit;
import com.google.common.collect.Lists;
import com.google.common.collect.Maps;
import java.util.List;
import java.util.Map;

/**
 * This class is generated by Jdbc code generator.
 * <p>
 * Table : device remarks: 设备表
 *
 * @author Jdbc Code Generator Date
 */
public class DeviceKit implements PersistentKit<Integer, Device> {


  @Override
  public List<String> fields() {
    return Lists.newArrayList("deviceId",
        "parentId",
        "isVirtual",
        "companyCode",
        "name",
        "barcode",
        "macAddress",
        "encryptKey",
        "type",
        "isOnline",
        "addOn",
        "createdOn");
  }

  @Override
  public String primaryField() {
    return "deviceId";
  }

  @Override
  public void toMap(Device device, Map<String, Object> map) {
    map.put("deviceId", device.getDeviceId());
    map.put("parentId", device.getParentId());
    map.put("isVirtual", device.getIsVirtual());
    map.put("companyCode", device.getCompanyCode());
    map.put("name", device.getName());
    map.put("barcode", device.getBarcode());
    map.put("macAddress", device.getMacAddress());
    map.put("encryptKey", device.getEncryptKey());
    map.put("type", device.getType());
    map.put("isOnline", device.getIsOnline());
    map.put("addOn", device.getAddOn());
    map.put("createdOn", device.getCreatedOn());
  }

  @Override
  public void fromMap(Map<String, Object> map, Device device) {

  }
  /* START Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/
  /* END Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/


}
