package com.github.edgar615.util.mybatis;

import com.github.edgar615.util.mybatis.BaseMapper;
import com.github.edgar615.util.search.Example;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.cache.annotation.CacheConfig;
import org.springframework.cache.annotation.CacheEvict;
import org.springframework.cache.annotation.Cacheable;

/**
 * This class is generated by Jdbc code generator.
 *
 * Table : sys_user
 *
 * @author Jdbc Code Generator Date 2019-03-25
 */
@Mapper
@CacheConfig(cacheResolver = "mybatisJdbcCacheResolver")
public interface SysUserMapper extends BaseMapper<Long, SysUser> {

  /**
   * 新增数据.
   *
   * @param persistent 持久化对象
   */
  @Override
  @CacheEvict(cacheNames = "SysUserJdbcCache", key = "'SysUser:' + #p0.id()")
  void insert(SysUser persistent);

  /**
   * insert一条数据，并返回自增主键
   *
   * @param persistent 持久化对象
   */
  @Override
  @CacheEvict(cacheNames = "SysUserJdbcCache", key = "'SysUser:' + #result")
  Long insertAndGeneratedKey(SysUser persistent);

  /**
   * 根据主键删除.
   *
   * @param id 主键
   * @return 删除记录数
   */
  @Override
  @CacheEvict(cacheNames = "SysUserJdbcCache", key = "'SysUser:' + #p1")
  int deleteById(Long id);

  /**
   * 根据条件删除.
   *
   * @param example 查询条件
   * @return 删除记录数
   */
  @Override
  @CacheEvict(cacheNames = "SysUserJdbcCache", allEntries = true)
  int deleteByExample(@Param("example") Example example);

  /**
   * 根据主键更新，忽略实体中的null.
   *
   * @param persistent 持久化对象
   * @param id 主键
   * @return 修改记录数
   */
  @Override
  @CacheEvict(cacheNames = "SysUserJdbcCache", key = "'SysUser:' + #p1")
  int updateById(@Param("persistent") SysUser persistent, @Param("id") Long id);

  /**
   * 根据条件更新，忽略实体中的null.
   *
   * @param persistent 持久化对象
   * @param example 查询条件
   * @return 修改记录数
   */
  @Override
  @CacheEvict(cacheNames = "SysUserJdbcCache", allEntries = true)
  int updateByExample(@Param("persistent") SysUser persistent, @Param("example") Example example);

  /**
   * 根据主键更新，忽略实体中的null
   *
   * @param persistent 持久化对象
   * @param addOrSub 需要做增加或者减去的字段，value为正数表示增加，负数表示减少
   * @param nullFields 需要设为null的字段
   * @param id 主键ID
   * @return 修改记录数
   */
  @Override
  @CacheEvict(cacheNames = "SysUserJdbcCache", key = "'SysUser:' + #p3")
  int updateByIdWithNull(@Param("persistent") SysUser persistent, @Param("addOrSub") Map<String, Number> addOrSub,
      @Param("nullFields") List<String> nullFields,
      @Param("id") Long id);

  /**
   * 根据条件更新，忽略实体中的null
   *
   * @param persistent 持久化对象
   * @param addOrSub 需要做增加或者减去的字段，value为正数表示增加，负数表示减少
   * @param nullFields 需要设为null的字段
   * @param example 查询条件
   * @return 修改记录数
   */
  @Override
  @CacheEvict(cacheNames = "SysUserJdbcCache", allEntries = true)
  int updateByExampleWithNull(@Param("persistent") SysUser persistent, @Param("addOrSub") Map<String, Number> addOrSub,
      @Param("nullFields") List<String> nullFields, @Param("example") Example example);


  /**
   * 根据主键查找.
   *
   * @param id 主键
   * @return 持久化对象，如果未找到任何数据，返回null
   */
  @Override
  @Cacheable(cacheNames = "SysUserJdbcCache", key = "'SysUser:' + #p1")
  SysUser findById(Long id);

  /* START Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/
  /* END Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/
}
